spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ecnu?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: ecnu
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 10000
      connection-timeout: 60000
      validation-timeout: 3000
      login-timeout: 15
      max-lifetime: 60000
      maximum-pool-size: 50
      connection-test-query: "select 1"
  rabbitmq:
    host: 192.168.1.7
    port: 5672
    username: ecnu
    password: xxx
    publisher-returns: true
    virtual-host: sei

wechat:
  cp:
    corpId: wwa4fxxxbd27110b # 企业ID 在此页面查看：https://work.weixin.qq.com/wework_admin/frame#profile）
    appConfigs:
      - agentId: 1000002 #（某一具体应用的AgentId，如果是要配置通讯录同步的应用，可以随便配置一个）
        secret: LFR72gtRLz0Rxxxxx8 #（该应用的Secret）
        token: 111 #（应用中的 “接受消息” 部分的 “接收消息服务器配置” 里的Token值）
        aesKey: 111 #（应用中的 “接受消息” 部分的 “接收消息服务器配置” 里的EncodingAESKey值）
    sei-agentId: 1000002

# The OAuth2 server definition that would be used to send the authorization requests to
authserver:
  hostname: http://127.0.0.1
  port: 8398
  contextPath: auth
  schema: http

# Note that the "/user" endpoint needs to provide the principle of the logged in user (/me endpoint)
security:
  oauth2:
    resource:
      jwt:
        key-value: EbtrhBlNpxxxxx
      #      user-info-uri: ${authserver.schema}://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
      user-info-uri: http://127.0.0.1:8398/me
      prefer-token-info: true
      token-info-uri: http://127.0.0.1:8398/oauth/token

ribbon:
  eureka:
    enabled: true
  #eureka客户端ribbon刷新时间
  #默认30s
  ServerListRefreshInterval: 5000

eureka:
  client:
    # 指定是否从注册中心获取服务(注册中心不需要开启)
    fetch-registry: true
    # 指定是否将服务注册到注册中心(注册中心不需要开启)
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9300/eureka
    #eureka client刷新本地缓存时间
    #默认30s
    registryFetchIntervalSeconds: 5
  #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
  #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
  #默认90s
  instance:
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5

#minio文件存储
minio:
  endpoint: http://127.0.0.1:9004
  accessKey: minioadmin
  accessValue: minioadmin
  bucket: sei
  fileType: png,jpg,jpeg,xls,xlsx,doc,pdf,docx,zip,rar,mpeg,avi,mp3
  imgType: png,jpg,jpeg #图片后缀

scheduled:
  activityStateRefreshTime: 60000 #活动状态刷新时间
  processStateRefreshTime: 60000 #过程状态刷新时间
  qrCodeDeleteTime: 600000 #二维码删除时间

templateUrl:
  url: \src\main\resources\file\
  fileUrl: C:\Applications\templateFile\ #临时备份文件地址，文件可删除

url:
  url: http://demosite.imwork.net/sca-client/#/
  phoneUrl: http://demosite.imwork.net/sca-h5/#/
  pcurl: http://demosite.imwork.net/sca-client/#/
  h5url: http://demosite.imwork.net/sca-h5/#/
  posterGeneratorUrl: http://localhost:8003/printer/print
  strapi: http://127.0.0.1:1397
  superset: http://192.168.1.123:8088/api/v1/chart/

interface:
  url: https://api.ecnu.edu.cn
  token: /oauth2/token
  organization: /api/v1/organization/list? #组织结构列表
  staff: /api/v1/user/profile/staff?userId= #教职工基本信息
  student: /api/v1/user/profile/student?userId= #学生基本信息
  staffAppointment: /api/v1/staff/gbrz/byuserid?userId= #教职工任职情况
  staffStudyExperience: /api/v1/staff/edu?userId= #教职工学习经历
  personnelTalents: /api/v1/customized/zzb/rsinfo?pageSize=1&pageNum=1&ts=0 #人事人才
  graduateStudent: /api/v1/customized/zzb/yjsinfo #研究生信息
  undergraduate: /api/v1/customized/zzb/bksinfo #本科生信息
  grantType: client_credentials
  clientId: 523xxxx3d
  clientSecret: b80626bxxxx673f00c1936ac